### ISSUE TITLE
Documentation Invalid Link

### ISSUE THREAD

**Issue by commonsguy** [copper-leaf/kotlin-json-forms#1]
In the project `README`, you have:

> See the [website](https://copper-leaf.github.io/json-forms/) for detailed documentation and usage instructions.

However, that link results in a 404. Were you aiming for https://copper-leaf.github.io/kotlin-json-forms/wiki/usage-guide/ instead?

**Comment by cjbrooks12** [comment]
Nice catch, yes that's the correct link. I've updated the README
